spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    tomcat:
      initial-size: 20
      max-active: 100
      max-idle: 100
      min-idle: 20
      max-wait: 10000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  jpa:
    show-sql: true
  application:
    name: Spring-Quartz-Scheduler
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            makeSchedulerThreadDaemon: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 25000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            makeThreadsDaemons: true
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
